### ISSUE TITLE
dependency errors

### ISSUE THREAD

**Issue by timdrysdale** [wvengen/inkscape-addons#3]
Many thanks for this extension. I'm probably making some installation error or there is a versioning issue - leaving this here in case anyone has similar issue.
Issue:  The multi-page option is not visible in the save-as options, despite following installation instructions.
OS/version: Ubuntu 20.04, Inkscape 0.92
Dependency checks: pdftk is installed and on the path; works from the command line

The `extension-error.log` is giving this output.

```
Extension "Multi-page PDF export" failed to load because a dependency was not met.
Dependency:
  type: executable
  location: path
  string: multi_page_pdf_output.py

Extension "Multi-page PDF export" failed to load because a dependency was not met.
Dependency:
  type: file
  location: path
  string: multi_page_pdf_output.py
```
I've not had time to troubleshoot further (other than noting that also doing `chmod +x ` on the py file did not appear to fix it, error occurs whether the `.py` file is executable or not)

```
/home/$USER/.config/inkscape
├── extension-errors.log
├── extensions
│   ├── multi_page_pdf_output.inx
│   └── multi_page_pdf_output.py
├── icons
├── keys
├── nohup.out
├── palettes
├── preferences.xml
└── templates
```
